site_name: ExStruct
site_url: https://harumiweb.github.io/exstruct/
theme:
  name: material
nav:
  - Home: index.md
  - API Reference: api.md
  - Concept / Why ExStruct?: concept.md
  - Read Me (EN): README.en.md
  - Read Me (JA): README.ja.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
